export enum ActionTypes {
  LOAD_FLIGHTS_FETCH = '@flight-map/LOAD_FLIGHTS_FETCH',
  LOAD_FLIGHTS_SUCCESS = '@flight-map/LOAD_FLIGHTS_SUCCESS',
  LOAD_FLIGHTS_ERROR = '@flight-map/LOAD_FLIGHTS_ERROR',
  FILTER_FLIGHTS_START = '@flight-map/FILTER_FLIGHTS_START',
  FILTER_FLIGHTS_SUCCESS = '@flight-map/FILTER_FLIGHTS_SUCCESS',
  FILTER_FLIGHTS_ERROR = '@flight-map/FILTER_FLIGHTS_ERROR',
}
