export enum ActionTypes {
  LOAD_AIRPORTS_FETCH = '@flight-map/LOAD_AIRPORTS_FETCH',
  LOAD_AIRPORTS_SUCCESS = '@flight-map/LOAD_AIRPORTS_SUCCESS',
  LOAD_AIRPORTS_ERROR = '@flight-map/LOAD_AIRPORTS_ERROR',
  FILTER_AIRPORTS_START = '@flight-map/FILTER_AIRPORTS_START',
  FILTER_AIRPORTS_SUCCESS = '@flight-map/FILTER_AIRPORTS_SUCCESS',
  FILTER_AIRPORTS_ERROR = '@flight-map/FILTER_AIRPORTS_ERROR',
}
